theme: jekyll-theme-minimal
title: Serene Scene Events
description: Creating serene moments for lifeâ€™s special occasions
defaults:
  -
    scope:
      path: ""
    values:
      permalink: /:basename/
